trigger:
- releases/3.1.x

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: Bash@3
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.sh
      arguments: --azure-pipelines

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.x SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: PowerShell@2
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.ps1  
      arguments: --azure-pipelines
  - task: NuGetCommand@2
    displayName: 'Push packages'
    inputs:
      command: push
      packagesToPush: 'nuget/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(FEEDID)'
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
